#!/bin/bash
PKGS=`echo "$@" | python -c "import sys;print ' '.join(a.split('/')[-1] for a in sys.stdin.read().split())"`
if [ -e /usr/bin/yaourt ]
then
    yaourt -Rns "$PKGS"
else
    pacman -Rns "$PKGS"
fi
