#!/usr/bin/python
from itertools import chain
from random import choice, shuffle
from string import ascii_lowercase, ascii_uppercase, digits, punctuation
from sys import argv

w = 4
#if len(argv) > 1:
#    w = int(argv[1]) / 4
c = [(ascii_lowercase, w), (ascii_uppercase, w), (digits, w), (punctuation, w)]
v = list(chain(*([choice(vs) for _ in range(cx)] for vs, cx in c)))

shuffle(v)
print(''.join(v))
