#!/usr/bin/python
import random
import string
import sys

c = string.ascii_letters + string.digits
w = 10

if len(sys.argv) > 1:
    w = int(sys.argv[1])

print(''.join((random.choice(c) for _ in range(w))))
