#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import datetime
import sys
import textwrap
import urllib
import lxml.html.soupparser as soup


url = 'http://forums.steampowered.com/forums/'
thread_path = 'printthread.php?t=784745'


def make_argparser():
    parser = argparse.ArgumentParser(
	description='Show Posts in Steam Downtime Announcements Thread')
    parser.add_argument('-n', '--num', default=3, type=int,
			help='Number of posts to show')
    parser.add_argument('-w', '--width', default=72, type=int,
			help='Word wrap width')
    parser.add_argument('-g', '--given-date', action='store_true',
			help='Print given date, not local date.', )
    return parser


def local_date(value):
    # 08-31-2010 06:29 AM
    dt = datetime.datetime.strptime(value, '%m-%d-%Y %I:%M %p')


if __name__ == '__main__':
    args = make_argparser().parse_args(sys.argv[1:])
    txt = urllib.urlopen(url + thread_path)
    ele = soup.fromstring(txt)
    nav = ele.xpath(".//div[attribute::class='pagenav']")[0]
    last_path = nav.xpath(".//td[position()=last()]/a")[0].attrib['href']
    txt = urllib.urlopen(url + last_path)
    ele = soup.fromstring(txt)

    posts = ele.xpath(".//table[attribute::class='tborder']")
    for post in posts[-args.num:]:
	author, date = [e.text for e in post.xpath('tr/td/table/tr/td')]
	ann = post.xpath(".//div")[0].text_content()
	print '{0} -- posted by {1}'.format(date, author)
	for line in textwrap.wrap(ann, args.width):
	    print line
	print
