#!/bin/bash
CPU=`sensors|grep temp1|cut -f 9 -d " " | sed s/\+// | sed s/°C//`
GPU=`nvidia-smi -a -q 2>/dev/null |grep Temp -A 2|grep Gpu|cut -f 2 -d ":" | sed s/\ //|sed s/\ C//`
FS="%-12s%.1f°C\t%.1f°F\n"
printf "$FS" "CPU" "$CPU" `units "tempC($CPU)" tempF -t`
printf "$FS" "GPU" "$GPU" `units "tempC($GPU)" tempF -t`
