#!/usr/bin/env python2
import sys
import urllib
from BeautifulSoup import BeautifulSoup


def get_url(word):
    return "http://thesaurus.com/browse/{word}".format(word=word)


def get_soup(data):
    return BeautifulSoup(data.replace("</scr' + 'ipt>", "</script>"))


def get_content(soup):
    return soup.findAll("table", {"class":"the_content"})


def put_content(table):
    find = table.find
    word = find(text="Main Entry:").parent.findNextSibling("td").string
    part = find(text="Part of Speech:").parent.findNextSibling("td").find("i").string
    print 'Word: {word}'.format(word=word)
    print 'Part of Speech: {part}'.format(part=part)

    syns = find(text='Synonyms:').parent.findNextSibling('td').findAll('a')
    if syns:
	syns = [syn.string for syn in syns]
	print 'Synonyms: {syns}'.format(syns=', '.join(syns))
    print


def main(args=None):
    if not args:
	return
    s = get_soup(urllib.urlopen(get_url(args[0])).read())
    for t in get_content(s):
	put_content(t)

if __name__ == '__main__':
    main(sys.argv[1:])
